### DISCUSSION TITLE
`- callout` parameters lead to errors

### DISCUSSION THREAD

**Discussion by vamonk** [mkdocs-publisher/mkdocs-publisher#101] [Q&A] [answered]
I have another question. I can't solve the following problem: 

ERROR   -  Config value 'plugins': Invalid config options for the 'pub-obsidian' plugin.
Aborted with a configuration error! 

This is the block I copied from the documentary:

```
plugins:
  - pub-obsidian:
    callouts:
      enabled: true
      indentation: spaces
```

Also a build is not possible: 

Aborted with a configuration error!

Thank you very much for your help.

**Comment by mkusz** [comment]
It's my bad, but:

1. In general, the values you see in documentation (and you have pasted) are by default enabled, so if you want them to be used, you don't have to redefine them. The only thing that is needed is to enable `pub-plugin` and all callouts will be working:
```
plugins:
  - pub-obsidian
```
2. If you want to change some of those values, you need to change an indentation like that (I will fix it in the documentation):
```
plugins:
  - pub-obsidian:
      callouts:
        enabled: true
        indentation: spaces
```

Thanks for point it.

**Comment by vamonk** [comment]
Unfortunately, the callouts are still not interpreted. With or without config. 

![image](https://github.com/user-attachments/assets/35ef79a0-3095-40c9-bcfb-84739a00de08)


This is my current yaml:

```
site_name: My Docs

theme: material

plugins:
  - pub-obsidian:
      callouts:
        enabled: true
        indentation: spaces
```
I would be very happy about further help, your solution is currently the best solution to publish Obsidian. I have now tested 3 others intensively and would love to use your solution.
