### DISCUSSION TITLE
Issue with pub-obsidian and .md-button

### DISCUSSION THREAD

**Discussion by nica-ev** [mkdocs-publisher/mkdocs-publisher#111] [Q&A] [answered]
My site is setup with the materials theme.

Materials give you the option to use { .md-button } as an attribute behind the links to turn them into a button.
This works flawless with markdown-style links like this `[text](text.md){ .md-button }`
With pub-obsidian enabled i was expecting to be able to write `[[text]]{ .md-button }` and achieve the same result.
Unfortunately this doesnt work. The link gets shown as normal text and the attached attribute appears as text in the resulting site.

Am i missing something or did i understand something wrong?
I would love to be able to utilize pub-obsidian, specially for the backlinking support - but i rely on the buttons for design / accessability purposes.
I also realized it might be a conflict with another plugin/extension, so here is my full mkdocs.yml

```
# Project information
site_name: NICA e.V. Documentation
site_url: https://nica-ev.github.io/docs/
site_author: Marc Bielert
site_description: Dokumentationen über Prozesse und Abläufe des Vereines NICA e.V.

# Repository
repo_name: nica-ev/docs
repo_url: https://github.com/nica-ev/docs

# Copyright
copyright: MIT 3.0

# Theme
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: primary
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mod
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.tracking
    - navigation.path
    - navigation.prune
    - toc.follow
    - header.autohide

markdown_extensions:
  - nl2br # treats markdown linebreaks as hard breaks
  - admonition # enables the use of callouts
  - toc:
      permalink: true  
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search    # enables search bar
 # - callouts  # translates obsidian callouts syntax to markdown syntax
  - pub-obsidian
  - tags:
      tags_file: tags.md

```

**Comment by mkusz** [comment]
Hi @nica-ev 

It's seems that this is a bug related to backlinks. As a temporary workaround you can disable backlinks and it should start to work. Never the less, I will work on a fix for it. To disable only backlinks functionality, you can add this below config to `mkdocs.yml` fils:

```yaml
  - pub-obsidian:
      backlinks:
        enabled: false
 ```
