### ISSUE TITLE
Obsidian plugin internal links with folders

### ISSUE THREAD

**Issue by ALameLlama** [mkdocs-publisher/mkdocs-publisher#106]
### Bug description

Hey,

I was playing around with folders and noticed they don't work.

I have an `docs/index.md` with
```
---
created: 2024-11-23 21:23
parent:
  - []
publish: "true"
---

---
## 📝 Notes
[[Something]]
```

And then a folder with
`docs/Something/Something.md`

In Obsidian this internal link works but on mkdocs it will try to route it to `localhost:8000/Something.md` instead of localhost:8000/Something/Something.md

I've also tried changing the folder name, in case it was because they are named the same, and that caused the issue, but no dice.

I also tried to enable backlinks but instead, that seemed to just add some hash that's visible on the screen

![image](https://github.com/user-attachments/assets/7dbe2c3b-3d04-4d41-ae2f-645977880327)

### Expected behaviour

Internal links should work the same way they do in Obsidian and be able to link to other pages

I'm also not sure if the hash for backlinks should be visible.

### Reproduction steps

Create a note with an internal link to another note that's within a folder.

### Operating system

Linux

### Python version

Other

### Contact details

nicholasaciechanowski@gmail.com

**Comment by ALameLlama** [comment]
> Python version
I am using 3.13 from a docker image I quickly made https://github.com/ALameLlama/mkdocs-publisher-image

**Comment by mkusz** [comment]
Can you share yours `mkdocs.yml` file with me?

**Comment by ALameLlama** [comment]
```
site_name: Llama's Notes
site_url: "https://notes.mydomain.au/"
theme:
  name: material
  # logo: assets/flame.svg
  # favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - pub-obsidian:
      obsidian_dir: .obsidian
      templates_dir: Templates
      backlinks:
        enabled: false
```

This is what I was testing with, and setting 
```
plugins:
  - pub-obsidian:
      obsidian_dir: .obsidian
      templates_dir: Templates
      backlinks:
        enabled: true
```

to recreate the issue

**Comment by mkusz** [comment]
It seems like you are missing some settings and some are not needed. First of all, the missing settings are my fault because they are not mentioned in the documentation. So start with it. You need to add this section to yours `mkdocs.yal` file:
```yaml
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
```
I'm not fully sure it those are all that is needed. Just let me know if it works.
As for some not needed values, take a look at this:
```yaml
plugins:
  - pub-obsidian:
      templates_dir: Templates
```
This is an equivalent to your config. You don't need to provide the same values as one that are default. Also backlinks are enabled by default when you add `pub-obsidian` to the plugin section. The only value that is different, is your name for the template directory.

**Comment by ALameLlama** [comment]
That's looking better, it's using hiding the hash now, but it still has
```
Backlinks:
??? backlink "None" 
```

https://github.com/user-attachments/assets/38e15301-a365-4918-b401-f07f88693a6a

am I also miss understand this line?
https://github.com/mkdocs-publisher/mkdocs-publisher/blob/main/mkdocs_publisher/obsidian/backlinks.py#L67

I thought setting the site_url in the config would override what I assume is coming from the mkdoc serve command.

**Comment by mkusz** [comment]
Thanks for all your testing.

So try to fix those `??? backlink` things. I have tested it on one of my own pages and it seems that the minimal required set of `markdown_extensions` is as follow:
```yaml
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
```
Adding `md_in_html` should solve this issue.

As for not working links, let's try to add `dev_addr` value as follow
```yaml
site_name: Llama's Notes
site_url: "https://notes.mydomain.au/"
dev_addr: 127.0.0.1
# or
dev_addr: 127.0.0.1:8123
```
On some systems (probably mostly on MacOS) you need to provide local host address as `127.0.0.1` not as `0.0.0.0`.

There could be also one potential setting that is missing in your `mkdocs.yml` file:
```yaml
use_directory_urls: true
```
It should be close to `site_url` on the same indentation level.

The line you have mentioned:
```python
backlink_link = f"{self._mkdocs_config.site_url}{page.url}{original_link.backlink_anchor}"
```
is constructed like this:
- `self._mkdocs_config.site_url` is a domain name part, in your case it will be a `site_url` (for `mkdocs build` command) or `dev_addr` (for `mkdocs serve` command)
- `page.url` is a subdirectory part of a link (for example `home/`)
- `original_link.backlink_anchor` is an anchor link to a backlink (this is this wired hash you have seen, like this one `#abb0de8633b560c832e90de67720c83f`).

Please let me know if this helped, so I can add some additional information into documentation.

**Comment by ALameLlama** [comment]
Adding that plugins seems to be better, I can see to creating a drop down with the title "None", I'm not sure that entirely correct.

I tried to set the dev_addr and that didn't seem to do anything, I have this running under unraid (slackware linux) using this docker container [ALameLlama/mkdocs-publisher-image](https://github.com/ALameLlama/mkdocs-publisher-image) which is why it was done using 0.0.0.0 so it's accessible from other sources then localhost.

the site_url option doesn't seem to be working. I have it set to the domain that notes are hosted on but it's still returning 0.0.0.0:8000 on the links which is what the docker container uses when it runs mkdoc serve but I don't think this is issue with the plugin and this is a PEBCAK on my end so I'll try and play around with that to see if I can get that working.

Thanks for your help :)

```
site_name: Llama's Notes
use_directory_urls: true
site_url: "https://notes.mydomain.au/"

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - pub-obsidian

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
 ```
