### ISSUE TITLE
Ungraceful fail when parsing configuration for pub-debug

### ISSUE THREAD

**Issue by mdbenito** [mkdocs-publisher/mkdocs-publisher#116]
### Bug description

I'm not sure one can call this a bug, but I think it merits addressing, even if only by being more explicit in the documentation.

A mistype in the config, from a correct
```yaml
  - pub-debugger:
      console_log:
        enabled: true
        log_level: WARNING
```
to an incorrect
```yaml
  - pub-debugger:
      console_log:
        enabled: true
        log_level: warning
```
will fail catastrophically (and rather obscurely) with a stacktrace ending in:
```
  File "blahblah/venv/lib/python3.10/site-packages/mkdocs_publisher/debugger/plugin.py", line 75, in __init__
    if self.config.console_log.enabled:
AttributeError: 'dict' object has no attribute 'enabled'
```

This seems to be due to the strict parsing done by `option.Choice` in `_Debugger*Config`:

```python
    log_level = option.Choice(choices=logging._nameToLevel.keys(), default="INFO")
```

I guess some additional validation should be done in the plugin's init, but I'm not familiar with mkdocs at all, so maybe there's some standard solution to this.

At any rate, I believe a quick mention in the docs as to what the valid values are would help.

### Expected behaviour

An informative error message of the kind "invalid log_level BLAH, valid choices are: [whole list here]"

### Reproduction steps

Just make a typo in the config for `log_level`

### Operating system

Windows, Linux

### Python version

3.9, 3.10

### Package versions

```
mkdocs                                    1.6.1
mkdocs-alias-plugin                       0.9.0
mkdocs-autorefs                           1.4.0
mkdocs-bibtex                             4.2.3
mkdocs-gen-files                          0.5.0
mkdocs-get-deps                           0.2.0
mkdocs-git-revision-date-localized-plugin 1.4.1
mkdocs-glightbox                          0.4.0
mkdocs-literate-nav                       0.6.1
mkdocs-macros-plugin                      1.3.7
mkdocs-material                           9.6.7
mkdocs-material-extensions                1.3.1
mkdocs-publisher                          1.4.6
mkdocs-section-index                      0.3.9
mkdocstrings                              0.28.2
mkdocstrings-python                       1.16.2
```

**Comment by mkusz** [comment]
Hi @mdbenito and thanks for this report.
Unfortunately, this is pure mkdocs internals. I will add the possibility to use small case lob level names and add this information to the documentation, but for mkdocs I'm not sure if it's an easy fix. I will take a deeper look and report this kind of issue to the mkdocs main project.

**Comment by mkusz** [comment]
Hi @mdbenito 
I have made a v1.4.7 branch that should fix this issue. Can you instal mkdocs-publisher from this branch and test it?

**Comment by mdbenito** [comment]
I think the log_level setting is not respected any more. I have:

```yaml
plugins:
  - pub-debugger:
      file_log:
        enabled: false
      zip_log:
        enabled: false
      console_log:
        enabled: true
        log_level: WARNING   # I tested warning too with the same effect (no more fail, but no filtering)
        show_code_link: false
        show_entry_time: false
        show_logger_name: true
        show_deprecation_warnings: false
```

And yet I see:

```log
[INFO ] Found branch name using git: develop [mkdocs]
[INFO ] Building documentation... [mkdocs.commands.serve]
[INFO ] [macros] - No default module `main` found [mkdocs.plugins.mkdocs_macros.util]
[INFO ] FutureWarning: The 'import' key is renamed 'inventories' for the Python handler
  File "/home/miguel/miniconda3/envs/pydvl3.9/lib/python3.9/site-packages/mkdocstrings/handlers/base.py", line 682, in get_handler
    self._handlers[name] = module.get_handler(**kwargs)
  File "/home/miguel/miniconda3/envs/pydvl3.9/lib/python3.9/site-packages/mkdocstrings_handlers/python/handler.py", line 370, in get_handler
    warn("The 'import' key is renamed 'inventories' for the Python handler", FutureWarning, stacklevel=1)
 [mkdocs.__main__]
[INFO ] Loading data from bib files: ['docs/assets/pydvl.bib'] [mkdocs.plugins.mkdocs-bibtex]
```
